<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_Test" Id="{e4d4bf79-85f5-437e-b658-fbd7d863578f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Test
VAR
	fbMoveAbsoluteTest : FB_MoveAbsolute_Test;
	fbMoveModuloTest : FB_MoveModulo_Test;
	fbMoveVelocity : FB_MoveVelocity_Test;
	fbMoveRelativeTest : FB_MoveRelative_Test;
	fbJogTest : FB_Jog_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* UnitTest *)
RUN();

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>